# (c) All rights reserved. ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2017
---
language: python

python:
- '3.6'

install:
- pip install -e requirements/base.txt

script:
- pytest src/test